package com.clarizen.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-04-10T08:40:54.429-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "Clarizen", 
                  wsdlLocation = "https://api.clarizen.com/v1.0/Clarizen.svc",
                  targetNamespace = "http://clarizen.com/api") 
public class Clarizen extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://clarizen.com/api", "Clarizen");
    public final static QName Clarizen = new QName("http://clarizen.com/api", "Clarizen");
    static {
        URL url = null;
        try {
            url = new URL("https://api.clarizen.com/v1.0/Clarizen.svc");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Clarizen.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://api.clarizen.com/v1.0/Clarizen.svc");
        }
        WSDL_LOCATION = url;
    }

    public Clarizen(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Clarizen(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Clarizen() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IClarizen
     */
    @WebEndpoint(name = "Clarizen")
    public IClarizen getClarizen() {
        return super.getPort(Clarizen, IClarizen.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IClarizen
     */
    @WebEndpoint(name = "Clarizen")
    public IClarizen getClarizen(WebServiceFeature... features) {
        return super.getPort(Clarizen, IClarizen.class, features);
    }

}
